In [48]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import pandas as pd
pd.__version__

'0.24.2'

In [49]:
df = pd.read_csv("https://gist.githubusercontent.com/cscheffler/482412b75d7b7c8ab83dd86e81d71403/raw/9ed65a9d2bb8455e4b225400f57f2d77f851aec9/socialmobility.csv", sep=",")
df

father           son  count
0           farm          farm    703
1           farm     unskilled   1478
2           farm       skilled   1430
3           farm  professional   1109
4      unskilled          farm     58
5      unskilled     unskilled   1756
6      unskilled       skilled   1630
7      unskilled  professional   1568
8        skilled          farm     63
9        skilled     unskilled   1453
10       skilled       skilled   2068
11       skilled  professional   2483
12  professional          farm     61
13  professional     unskilled    749
14  professional       skilled   1183
15  professional  professional   3315

As we can see from above, this is a multinomial distribution, since there are multiple identical independent trials where each trial has 𝑘 possible outcomes.

We were also asked to choose a Dirichlet prior to have a uniform distribution over the probability vector parameter of the multinomial.

Therefore, we will need to select a Dirichlet prior, which is the conjugate to a multinomial likelihood.

According to <a href="https://en.wikipedia.org/wiki/Conjugate_prior#Table_of_conjugate_distributions">Wikipedia</a>, the Dirichlet prior has $\alpha$ as its prior hyperparameter.

Therefore, to calculate the posterior hyperparameters, we will have to use the following formula:
<br>
<center>${\displaystyle {\boldsymbol {\alpha }}+\sum _{i=1}^{n}\mathbf {x} _{i}\!}$</center>

where $x$ is the number of individual trials.

In [64]:
# Finding the number of trials conducted for each group

farm = sum(df.loc[lambda df: df.father == 'farm', 'count'])
unskilled = sum(df.loc[lambda df: df.father == 'unskilled', 'count'])
skilled = sum(df.loc[lambda df: df.father == 'skilled', 'count'])
professional = sum(df.loc[lambda df: df.father == 'professional', 'count'])
print(f"There were {farm} fathers that were farmers, {unskilled} fathers that were unskilled, {skilled} fathers that were skilled, and {professional} fathers that were professionals.")

There were 4720 fathers that were farmers, 5012 fathers that were unskilled, 6067 fathers that were skilled, and 5308 fathers that were professionals.


In [63]:
# Setting up the Dirichlet prior

dirichlet = stats.dirichlet([1, 2, 3, 4])
num_samples = 4
print('Generating', num_samples, 'samples:')
samples = dirichlet.rvs(size=num_samples)
print(samples)
print('')
print('Sum of each sample (should be 1):')
print(samples.sum(axis=1))
print('')
print('Value of probability density function at each sample:')
print(dirichlet.pdf(samples.transpose()))

Generating 4 samples:
[[0.07015414 0.14429606 0.34790591 0.43764389]
 [0.18763825 0.13502804 0.41537149 0.26196223]
 [0.08321873 0.30398893 0.22893338 0.38385896]
 [0.105482   0.42474641 0.2931602  0.17661139]]

Sum of each sample (should be 1):
[1. 1. 1. 1.]

Value of probability density function at each sample:
[44.27132166 12.66470665 27.25039761  6.08103741]


In [69]:
# For father == farm:
mult_farm = stats.multinomial(farm, [1/4, 1/4, 1/4, 1/4])
num_samples = 4
print('Generating', num_samples, 'samples for father == farm:')
samples_farm = mult_farm.rvs(size=num_samples)
print(samples_farm)
print('')
print('Value of probability mass function at farm samples:')
print(mult_farm.pmf(samples_farm))
print('')

# Multiplying the Dirichlet prior by the multinomial likelihood:
print('Dirichlet posterior is:')
print(dirichlet.pdf(samples.transpose())*mult_farm.pmf(samples_farm))

Generating 4 samples for father == farm:
[[1144 1202 1190 1184]
 [1202 1205 1189 1124]
 [1192 1161 1176 1191]
 [1200 1136 1237 1147]]

Value of probability mass function at farm samples:
[1.39702523e-06 4.92175621e-07 2.38520122e-06 1.86885540e-07]

Dirichlet posterior is:
[6.18481533e-05 6.23325987e-06 6.49976817e-05 1.13645796e-06]


In [73]:
# For father == unskilled:
mult_unskilled = stats.multinomial(unskilled, [1/4, 1/4, 1/4, 1/4])
num_samples = 4
print('Generating', num_samples, 'samples for father == unskilled:')
samples_unskilled = mult_unskilled.rvs(size=num_samples)
print(samples_unskilled)
print('')
print('Value of probability mass function at unskilled samples:')
print(mult_unskilled.pmf(samples_unskilled))
print('')

# Multiplying the Dirichlet prior by the multinomial likelihood:
print('Dirichlet posterior is:')
print(dirichlet.pdf(samples.transpose())*mult_unskilled.pmf(samples_unskilled))

Generating 4 samples for father == unskilled:
[[1264 1340 1227 1181]
 [1246 1258 1231 1277]
 [1286 1252 1210 1264]
 [1232 1241 1222 1317]]

Value of probability mass function at unskilled samples:
[1.31911604e-08 1.82139939e-06 8.40623261e-07 3.08477345e-07]

Dirichlet posterior is:
[5.83990104e-07 2.30674889e-05 2.29073181e-05 1.87586228e-06]


In [74]:
# For father == skilled:
mult_skilled = stats.multinomial(skilled, [1/4, 1/4, 1/4, 1/4])
num_samples = 4
print('Generating', num_samples, 'samples for father == skilled:')
samples_skilled = mult_skilled.rvs(size=num_samples)
print(samples_skilled)
print('')
print('Value of probability mass function at skilled samples:')
print(mult_skilled.pmf(samples_skilled))
print('')

# Multiplying the Dirichlet prior by the multinomial likelihood:
print('Dirichlet posterior is:')
print(dirichlet.pdf(samples.transpose())*mult_skilled.pmf(samples_skilled))

Generating 4 samples for father == skilled:
[[1528 1523 1495 1521]
 [1521 1527 1512 1507]
 [1495 1488 1544 1540]
 [1516 1543 1524 1484]]

Value of probability mass function at skilled samples:
[1.72995639e-06 1.98539702e-06 9.17490927e-07 1.18041262e-06]

Dirichlet posterior is:
[7.65874557e-05 2.51444708e-05 2.50019926e-05 7.17813332e-06]


In [75]:
# For father == farm:
mult_professional = stats.multinomial(professional, [1/4, 1/4, 1/4, 1/4])
num_samples = 4
print('Generating', num_samples, 'samples for father == professional:')
samples_professional = mult_professional.rvs(size=num_samples)
print(samples_professional)
print('')
print('Value of probability mass function at professional samples:')
print(mult_professional.pmf(samples_professional))
print('')

# Multiplying the Dirichlet prior by the multinomial likelihood:
print('Dirichlet posterior is:')
print(dirichlet.pdf(samples.transpose())*mult_professional.pmf(samples_professional))

Generating 4 samples for father == professional:
[[1338 1363 1335 1272]
 [1317 1332 1375 1284]
 [1363 1275 1281 1389]
 [1342 1355 1291 1320]]

Value of probability mass function at professional samples:
[4.75625496e-07 5.25629175e-07 6.18915653e-08 1.07985813e-06]

Dirichlet posterior is:
[2.10565693e-05 6.65693931e-06 1.68656976e-06 6.56665766e-06]


I'm not sure how to calculate the 95% confidence interval over the posterior probability - the values that I got above seem awfully small.